import type { CatalogProduct } from '@/types/catalog'

export const mockCatalog: CatalogProduct[] = [
  { id: 'S18-001', sku: 'S18-001', name: 'Lamborghini LP5000', category: 'carro', brand_model: 'Lamborghini LP5000', manufacturer: 'GULY', collection_tag: 'Vintage', scale: '1:8', piece_count: 3970, sale_price_brl: 1564.4, image_url: '/products/S18-001.jpg', image_urls: ['/products/S18-001-frente.jpg', '/products/S18-001-lateral.jpg', '/products/S18-001-traseira.jpg', '/products/S18-001-caixa.jpg'], video_url: null, automotive_history: null, dimensions: null, spec_highlights: null, length_cm: null, height_cm: null, width_cm: null, quantity_available: 0 },
  { id: 'S18-002', sku: 'S18-002', name: 'BMW R1300GS', category: 'moto', brand_model: 'BMW R1300GS', manufacturer: 'GULY', collection_tag: 'Motocicleta', scale: '1:5', piece_count: 2489, sale_price_brl: 1827.44, image_url: '/products/S18-002.jpg', image_urls: ['/products/S18-002-lateral.jpg', '/products/S18-002-traseira.jpg', '/products/S18-002-caixa.jpg'], video_url: null, automotive_history: null, dimensions: null, spec_highlights: null, length_cm: null, height_cm: null, width_cm: null, quantity_available: 3 },
  { id: 'S18-003', sku: 'S18-003', name: '963 (Edição Limitada Cromada)', category: 'carro', brand_model: 'Porsche 963', manufacturer: 'GULY', collection_tag: 'Lemans', scale: '1:8', piece_count: 3069, sale_price_brl: 1287.52, image_url: '/products/S18-003.jpg', image_urls: ['/products/S18-003-frente.jpg', '/products/S18-003-lateral.jpg', '/products/S18-003-traseira.jpg', '/products/S18-003-aberto.jpg', '/products/S18-003-caixa.jpg'], video_url: null, automotive_history: null, dimensions: null, spec_highlights: null, length_cm: null, height_cm: null, width_cm: null, quantity_available: 14 },
  { id: 'S18-004', sku: 'S18-004', name: 'BMW M4 GT4', category: 'carro', brand_model: 'BMW M4 GT4', manufacturer: 'CBOX', collection_tag: 'Série GT', scale: '1:8', piece_count: 4556, sale_price_brl: 1739.36, image_url: '/products/S18-004.jpg', image_urls: ['/products/S18-004-frente.jpg', '/products/S18-004-traseira.jpg', '/products/S18-004-aberto.jpg', '/products/S18-004-motor.jpg', '/products/S18-004-interior.jpg', '/products/S18-004-caixa.jpg'], video_url: null, automotive_history: null, dimensions: null, spec_highlights: null, length_cm: null, height_cm: null, width_cm: null, quantity_available: 22 },
  { id: 'S18-005', sku: 'S18-005', name: 'Pagani Utopia', category: 'carro', brand_model: 'Pagani Utopia', manufacturer: 'CBOX', collection_tag: 'Supercarro', scale: '1:8', piece_count: 4688, sale_price_brl: 1353.66, image_url: '/products/S18-005.jpg', image_urls: [], video_url: null, automotive_history: null, dimensions: null, spec_highlights: null, length_cm: null, height_cm: null, width_cm: null, quantity_available: 8 },
  { id: 'S18-006', sku: 'S18-006', name: 'Lotus Exige Cup 430', category: 'carro', brand_model: 'Lotus Exige Cup 430', manufacturer: 'CADA', collection_tag: 'Supercarro', scale: '1:8', piece_count: 3730, sale_price_brl: 707.6, image_url: '/products/S18-006.jpg', image_urls: ['/products/S18-006-frente.jpg', '/products/S18-006-lateral.jpg', '/products/S18-006-traseira.jpg', '/products/S18-006-aberto.jpg', '/products/S18-006-motor.jpg', '/products/S18-006-caixa.jpg'], video_url: null, automotive_history: null, dimensions: null, spec_highlights: null, length_cm: null, height_cm: null, width_cm: null, quantity_available: 30 },
  { id: 'S18-007', sku: 'S18-007', name: 'Mazda Le Mans Rally 787B', category: 'carro', brand_model: 'Mazda 787B', manufacturer: 'CADA', collection_tag: 'Lemans', scale: '1:8', piece_count: 1797, sale_price_brl: 642.99, image_url: '/products/S18-007.jpg', image_urls: ['/products/S18-007-lateral.jpg', '/products/S18-007-traseira.jpg', '/products/S18-007-aberto.jpg', '/products/S18-007-caixa.jpg'], video_url: null, automotive_history: null, dimensions: null, spec_highlights: null, length_cm: null, height_cm: null, width_cm: null, quantity_available: 2 },
  { id: 'S18-008', sku: 'S18-008', name: 'Lamborghini Centenario', category: 'carro', brand_model: 'Lamborghini Centenario', manufacturer: 'CADA', collection_tag: 'Supercarro', scale: '1:8', piece_count: 3842, sale_price_brl: 1127.54, image_url: '/products/S18-008.jpg', image_urls: [], video_url: null, automotive_history: null, dimensions: null, spec_highlights: null, length_cm: null, height_cm: null, width_cm: null, quantity_available: 17 },
  { id: 'S18-009', sku: 'S18-009', name: 'Maserati Gran Turismo', category: 'carro', brand_model: 'Maserati Gran Turismo', manufacturer: 'REOBRIX', collection_tag: 'Supercarro', scale: '1:8', piece_count: 5480, sale_price_brl: 836.81, image_url: '/products/S18-009.jpg', image_urls: [], video_url: null, automotive_history: null, dimensions: null, spec_highlights: null, length_cm: null, height_cm: null, width_cm: null, quantity_available: 19 },
  { id: 'S18-010', sku: 'S18-010', name: 'Fórmula 1 Edição Especial', category: 'carro', brand_model: 'Fórmula 1', manufacturer: 'REOBRIX', collection_tag: 'Fórmula', scale: '1:8', piece_count: 3470, sale_price_brl: 916.8, image_url: '/products/S18-010.jpg', image_urls: [], video_url: null, automotive_history: null, dimensions: null, spec_highlights: null, length_cm: null, height_cm: null, width_cm: null, quantity_available: 25 },
  { id: 'S18-011', sku: 'S18-011', name: 'Bugatti Tourbillon', category: 'carro', brand_model: 'Bugatti Tourbillon', manufacturer: 'GULY', collection_tag: 'Supercarro', scale: '1:8', piece_count: 3719, sale_price_brl: 1518.25, image_url: '/products/S18-011.jpg', image_urls: ['/products/S18-011-frente.jpg', '/products/S18-011-acima.jpg', '/products/S18-011-traseira.jpg', '/products/S18-011-detalhe.jpg', '/products/S18-011-aberto.jpg', '/products/S18-011-caixa.jpg'], video_url: null, automotive_history: null, dimensions: null, spec_highlights: null, length_cm: null, height_cm: null, width_cm: null, quantity_available: 6 },
  { id: 'S18-012', sku: 'S18-012', name: 'Lamborghini Carro Conceito', category: 'carro', brand_model: 'Lamborghini Concept', manufacturer: 'GULY', collection_tag: 'Conceito', scale: '1:8', piece_count: 3601, sale_price_brl: 1748.99, image_url: '/products/S18-012.jpg', image_urls: [], video_url: null, automotive_history: null, dimensions: null, spec_highlights: null, length_cm: null, height_cm: null, width_cm: null, quantity_available: 11 },
  { id: 'S18-013', sku: 'S18-013', name: 'Nissan GTR Liberty Walk', category: 'carro', brand_model: 'Nissan GT-R', manufacturer: 'GULY', collection_tag: 'Supercarro', scale: '1:8', piece_count: 3939, sale_price_brl: 1656.7, image_url: '/products/S18-013.jpg', image_urls: [], video_url: null, automotive_history: null, dimensions: null, spec_highlights: null, length_cm: null, height_cm: null, width_cm: null, quantity_available: 28 },
  { id: 'S18-014', sku: 'S18-014', name: 'Ferrari Enzo', category: 'carro', brand_model: 'Ferrari Enzo', manufacturer: 'KBOX', collection_tag: 'Supercarro', scale: '1:8', piece_count: 4301, sale_price_brl: 1656.7, image_url: '/products/S18-014.jpg', image_urls: [], video_url: null, automotive_history: null, dimensions: null, spec_highlights: null, length_cm: null, height_cm: null, width_cm: null, quantity_available: 9 },
  { id: 'S18-015', sku: 'S18-015', name: 'Ferrari SF90 XX Stradale', category: 'carro', brand_model: 'Ferrari SF90 XX', manufacturer: 'GULY', collection_tag: 'Supercarro', scale: '1:8', piece_count: 3639, sale_price_brl: 1564.4, image_url: '/products/S18-015.jpg', image_urls: [], video_url: null, automotive_history: null, dimensions: null, spec_highlights: null, length_cm: null, height_cm: null, width_cm: null, quantity_available: 20 },
  { id: 'S18-016', sku: 'S18-016', name: 'Land Rover Discovery', category: 'carro', brand_model: 'Land Rover Discovery', manufacturer: 'GULY', collection_tag: 'Off Road', scale: '1:8', piece_count: 4817, sale_price_brl: 2072.0, image_url: '/products/S18-016.jpg', image_urls: ['/products/S18-016-frente.jpg', '/products/S18-016-lateral.jpg', '/products/S18-016-traseira.jpg', '/products/S18-016-detalhe.jpg', '/products/S18-016-caixa.jpg'], video_url: null, automotive_history: null, dimensions: null, spec_highlights: null, length_cm: null, height_cm: null, width_cm: null, quantity_available: 15 },
  { id: 'S18-017', sku: 'S18-017', name: 'Lamborghini Aventador SVJ', category: 'carro', brand_model: 'Lamborghini Aventador SVJ', manufacturer: 'KBOX', collection_tag: 'Supercarro', scale: '1:8', piece_count: 3811, sale_price_brl: 1656.7, image_url: '/products/S18-017.jpg', image_urls: [], video_url: null, automotive_history: null, dimensions: null, spec_highlights: null, length_cm: null, height_cm: null, width_cm: null, quantity_available: 4 },
]
